// <auto-generated />
namespace SistemaDeVendas.Aplicacao.Infraestrutura
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NovasEntidades : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NovasEntidades));
        
        string IMigrationMetadata.Id
        {
            get { return "201712052233564_NovasEntidades"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
